version: '3'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - .mongo:/data/db
    networks:
      - admin-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - .elasticsearch:/usr/share/elasticsearch/data
    networks:
      - admin-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  graylog:
    image: graylog/graylog:3.1
    volumes:
      - .graylog/data/journal:/usr/share/graylog/data/journal
      - .graylog/config:/usr/share/graylog/data/config
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=${RANDOM_SECRET}
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${ADMIN_PASSWORD_CRYPT_SHA256}
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.${CLUSTER_DOMAIN}/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
      - "514:514/udp"
    networks:
      - admin-net
      - traefik-net
  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure