version: '3.5'

services:
  traefik:
    image: traefik:2.0-alpine # The official Traefik docker image
    # command: --api --docker --docker.swarmMode --docker.watch --entryPoints='Name:http Address::80' --defaultentrypoints=http # Enables the web UI and tells Træfik to listen to docker
    command: --api --docker --docker.swarmMode --docker.watch --metrics.prometheus # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # HTTPS port
      - "3030:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ${DIR_PERSISTANT_FOLDER}/traefik/traefik.toml:/traefik.toml # configuration Traefik pour https et htaccess on managment webui
      - ${DIR_PERSISTANT_FOLDER}/traefik/acme.json:/acme.json 
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - metrics-net
      - traefik-net
    container_name: traefik

networks:
  traefik-net:
    external: true
    # "docker network create traefik-net --scope swarm -d overlay"
  metrics-net:
    external: true
    # "docker network create metrics-net --scope swarm -d overlay"

