version: '3.5'

services:
  mongodbGraylog:
    image: mongo:3
    volumes:
      - mongo_data:/data/db
    network:
      - admin-net
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "traefik-docker-swarm-cluster"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager 

  elasticsearchGraylog:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
    network:
      - admin-net
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "traefik-docker-swarm-cluster"

  graylog:
    image: graylog/graylog:3.1
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=${RANDOM_SECRET}
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${ADMIN_PASSWORD_CRYPT_SHA256}
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.${CLUSTER_DOMAIN}/
    links:
      - mongodbGraylog:mongo
      - elasticsearchGraylog
    depends_on:
      - mongodbGraylog
      - elasticsearchGraylog
    ports:
      # Graylog web interface and REST API
      - "9000"
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    deploy:
      labels:
        traefik.frontend.rule: Host:graylog.${CLUSTER_DOMAIN}
        traefik.port: 9000
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      network:
      - admin-net
      - traefik-net


# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local