version: '3.5'

services:
  dockerd-exporter:
    image: stefanprodan/dockerd-exporter:latest
    networks:
      - metrics-net
    environment:
      - DOCKER_GWBRIDGE_IP=${DOCKER_GWBRIDGE_IP}
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "dockerd-exporter-docker-swarm-cluster"

  node-exporter:
    image: flaviostutz/docker-swarm-node-exporter:0.14.5
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    networks:
      - metrics-net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "node-exporter-docker-swarm-cluster"
          
  cadvisor:
    image: google/cadvisor:v0.29.0
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - metrics-net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "cadvisor-docker-swarm-cluster"

  alertmanager:
    image: stefanprodan/swarmprom-alertmanager:v0.14.0
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-general}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ${DIR_PERSISTANT_FOLDER}/alertmanager:/alertmanager
    networks:
      - metrics-net
      - traefik-net
    deploy:
      labels:
        traefik.frontend.rule: Host:alertmanager.${CLUSTER_DOMAIN}
        traefik.port: "9093"
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic: "${HTACCESS_USER}:${HTACCESS_PASSWORD_CRYPT}"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "alertmanager-docker-swarm-cluster"

  unsee:
    image: cloudflare/unsee:v0.8.0
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    networks:
      - metrics-net
      - traefik-net
    deploy:
      labels:
        traefik.frontend.rule: Host:unsee.${CLUSTER_DOMAIN}
        traefik.port: "8080"
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic: "${HTACCESS_USER}:${HTACCESS_PASSWORD_CRYPT}"
      mode: replicated
      replicas: 1

  prometheus:
    image: stefanprodan/swarmprom-prometheus:v2.5.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1w'
    environment:
      - JOBS=traefik:8080
    volumes:
      - ${DIR_PERSISTANT_FOLDER}/prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
    networks:
      - metrics-net
      - traefik-net
    deploy:
      labels:
        traefik.frontend.rule: Host:prometheus.${CLUSTER_DOMAIN}
        traefik.port: "9090"
        traefik.docker.network: traefik-net
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "prometeus-docker-swarm-cluster"

  grafana:
    image: flaviostutz/docker-swarm-grafana:5.1.3
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ${DIR_PERSISTANT_FOLDER}/grafana:/var/lib/grafana
    networks:
      - metrics-net
      - traefik-net
    deploy:
      labels:
        traefik.frontend.rule: Host:grafana.${CLUSTER_DOMAIN}
        traefik.port: "3000"
        traefik.docker.network: traefik-net
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "grafana-docker-swarm-cluster"
          

networks:
  traefik-net:
    external: true
  metrics-net:
    external: true

configs:
  node_rules:
    file: ./prometheus/node.rules.yml
  task_rules:
    file: ./prometheus/task.rules.yml

