version: '3.5'

services:
  gitlab-runner1:
    image: flaviostutz/gitlab-runner
    environment:
      - GITLAB_URL=http://gitlab/
      - REGISTRATION_TOKEN=jPhhnDq7aRygyrMRzJ9e
      - DESCRIPTION=Runner1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DIR_PERSISTANT_FOLDER/gitlab-runner/etc:/etc/gitlab-runner
      - $DIR_PERSISTANT_FOLDER/gitlab-runner/home:/home/gitlab-runner
    deploy:
      labels:
        traefik.frontend.rule: Host:gitlab-runner1.${CLUSTER_DOMAIN}
        traefik.port: "80"
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
    networks:
      - traefik-net
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "gitlab-runner1-docker-swarm-cluster"

  #Gitlab server is here just for testing purposes of Gitlab Runner
  gitlab:
    image: gitlab/gitlab-ce:10.8.3-ce.0
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${CLUSTER_DOMAIN}'
    deploy:
      labels:
        traefik.frontend.rule: Host:gitlab.${CLUSTER_DOMAIN}
        traefik.port: "80"
        traefik.docker.network: traefik-net
      replicas: 1
    networks:
      - traefik-net
    volumes:
      - $DIR_PERSISTANT_FOLDER/gitlab/etc:/etc/gitlab
      - $DIR_PERSISTANT_FOLDER/gitlab/opt:/var/opt/gitlab
      - $DIR_PERSISTANT_FOLDER/gitlab/log:/var/log/gitlab
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.${CLUSTER_DOMAIN}:12201"
        tag: "gitlab-docker-swarm-cluster"

networks:
  traefik-net:
    external: true


